#The nexessary stuff/decessary stuff

base_url = "https://TrevorDales.github.io"
title = "Trevor Dales"
description = "Hi! My name is Trevor."
#generate_feed = false
compile_sass = true
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "shadharon"
taxonomies = [
    {name = "tags", feed = false},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
toc = false
use_cdn = false
search_bar = false

#Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = ""

#This header image is used for SEO. For example if you were to share an image via Messenger/Instagram/Twitter a preview picture is also presented
headerImage = ""

# The icon is display besides the menu text but is not necessary. It needs to be placed under "menu_icon" in the static "folder"
menu = [
    { name = "MAE 4190", url = "/experience", weight = 1, icon = "projects.png" },
    { name = "Contact", url = "/contact/contact", weight = 1, icon = "resume.png" }
]
#The icons available can be found in "social_icons" in the "static" folder
socials = [
    { name = "github", url = "https://github.com/TrevorDales", icon = "github" },
]


